GDA: FOLD_mixed
GDA_id: null
adv_scale: 0.0001
attention_dropout: 0.1
batch_size: 1024
betas:
- 0.9
- 0.999
checkpoints_path: checkpoints\DT-halfcheetah-medium-v2-identical-76c8
clip_grad: 0.25
conditioned: false
data_mixture_type: mixed
data_volume: 5000000.0
datapath: transformer/gpt_transformer/src/data/filtered/halfcheetah-medium-v2.npz
deterministic_torch: false
device: cpu
diffusion_backbone: mixer
diffusion_horizon: 31
embedding_dim: 128
embedding_dropout: 0.1
env: halfcheetah-medium-v2
episode_len: 1000
eval_episodes: 100
eval_every: 50000
eval_seed: 42
generation_type: s
group: DT-D4RL
guidance_target_multiple: 1.1
guidance_temperature: 1.2
iteration: 1
learning_rate: 0.0001
max_action: 1.0
max_timesteps: 100000
name: DT-halfcheetah-medium-v2-identical-76c8
num_heads: 1
num_layers: 3
num_workers: 4
project: '[NIPS]_halfcheetah-medium-v2'
residual_dropout: 0.1
reward_scale: 0.001
s4rl_augmentation_type: identical
seed: 0
seq_len: 20
std_scale: 0.0003
step: 100000
target_returns:
- 12000.0
uniform_scale: 0.0003
warmup_steps: 10000
weight_decay: 0.0001
